version: "3.1"

services:
  neo4j:
    image: neo4j:latest
    restart: always
    ports:
      - 7474:7474
      - 7687:7687
    environment: 
      NEO4J_AUTH: "neo4j/test" 
    labels:
      NAME: "neo4j-docker-compose"
    volumes:
      - "./neo4j/data:/data"
      - "./neo4j/logs:/logs"
      - "./neo4j/plugins:/plugins"
      - "./neo4j/import:/var/lib/neo4j/import"

  clickhouse:
    image: yandex/clickhouse-server
    restart: always
    ports:
      - 8123:8123
      - 9000:9000
      - 9009:9009
    labels:
      NAME: "clickhouse-docker-compose"
    volumes:
      - "./clickhouse/data:/var/lib/clickhouse"

  mongodb:
    image: mongo:4.2
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017
    labels:
      NAME: "mongodb-docker-compose"
    volumes:
      - "./mongodb:/data/db"

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: localhost
      POSTGRES_USER: postgres
    labels:
      NAME: "postgres-docker-compose"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  redis:
    image: bitnami/redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"
    volumes:
      - "./redis:/data"
    labels:
      NAME: "redis-docker-compose"

  rabbitmq:
    image: "rabbitmq:3.8-management"
    environment:
      RABBITMQ_ERLANG_COOKIE: "ERLANG_COOKIE"
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      NAME: "rabbitmq-docker-compose"
    volumes:
      - ./rabbitmq/data:/var/lib/rabbitmq
      - ./rabbitmq/data:/etc/rabbitmq/
